name: Run Vivado jobs over CPU testbench

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    # Use Ubuntu 20.04 because doxygen 1.8.13 from Ubuntu 18.04 is broken.
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Cache Xilinx Vivado 2019.1 package
        id: cache-vivado
        uses: actions/cache@v3
        env:
          cache-name: cache-vivado-package
        with:
            path: ~
            key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles("vivado_2019.1.tar.gz") }}
            restore-keys: |
              ${{ runner.os }}-${{ env.cache-name }}-
              ${{ runner.os }}-
      
      - if: ${{ steps.cache-vivado.outputs.cache-hit != 'true' }}
        name: Download Vivado 2019.1 package
        continue-on-error: true
        run: if [ ! -f ~/vivado_2019.1.tar.gz ]; then curl https://cernbox.cern.ch/remote.php/dav/public-files/xWjUduHViLUR9s4/Xilinx_Vivado_SDK_2019.1_0524_1430.tar.gz -o ~/vivado_2019.1.tar.gz; fi        

    # - name: Add ubuntu mirrors
    #   run: |
    #     # Github Actions caching proxy is at times unreliable
    #     # see https://github.com/actions/runner-images/issues/7048
    #     printf 'http://azure.archive.ubuntu.com/ubuntu\tpriority:1\n' | sudo tee /etc/apt/mirrors.txt
    #     curl http://mirrors.ubuntu.com/mirrors.txt | sudo tee --append /etc/apt/mirrors.txt
    #     sudo sed -i 's~http://azure.archive.ubuntu.com/ubuntu/~mirror+file:/etc/apt/mirrors.txt~' /etc/apt/sources.list

    # - name: Create Build Environment
    #   run: |
    #     sudo apt update
    #     sudo apt install doxygen python3-virtualenv
    #     sudo npm install -g less clean-css
    #     cmake -E make_directory ${{ runner.workspace }}/build

    # - name: Build
    #   working-directory: ${{ runner.workspace }}/build
    #   env:
    #     KEY: ${{ secrets.KEY }}
    #   run: $GITHUB_WORKSPACE/support/build-docs.py
